# Generated by Django 3.2.18 on 2024-02-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0007_alter_activecourseperiod_unique_together'),
        ('exam', '0006_auto_20240206_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupilreaction',
            name='is_correct',
        ),
        migrations.AlterField(
            model_name='pupilreaction',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active.pupl'),
        ),
    ]
