# Generated by Django 3.2.18 on 2024-02-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20240206_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pupil',
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
