# Generated by Django 3.2.18 on 2024-02-08 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0007_alter_activecourseperiod_unique_together'),
        ('exam', '0008_auto_20240207_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pupilreaction',
            name='pupil',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active.pupl'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pupilreaction',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
