# Generated by Django 3.2.18 on 2024-02-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20240208_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='degree',
            field=models.IntegerField(null=True),
        ),
    ]
