# Generated by Django 3.2.18 on 2024-02-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_exam_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
    ]
