# Generated by Django 3.2.18 on 2024-02-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_alter_exam_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
