# Generated by Django 3.2.18 on 2024-02-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20240215_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
