# Generated by Django 3.2.18 on 2024-01-11 16:52

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_class_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('online', 'online'), ('On site', 'On site')], default='online', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(default=5, null=True)),
                ('enrolled', models.IntegerField(blank=True, null=True)),
                ('payment', models.ImageField(blank=True, null=True, upload_to='payment_images/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='pupl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('payment', models.ImageField(blank=True, null=True, upload_to='payment_images/')),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='active.activecourse')),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('courses', models.ManyToManyField(blank=True, null=True, to='courses.Course')),
                ('periods', models.ManyToManyField(blank=True, null=True, to='timetable.periods')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCoursePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_field', models.CharField(max_length=100)),
                ('content', django_summernote.fields.SummernoteTextField(null=True)),
                ('active_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active.activecourse')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.periods')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='active.instructor')),
            ],
            options={
                'unique_together': {('active_course', 'period')},
            },
        ),
        migrations.AddField(
            model_name='activecourse',
            name='periods',
            field=models.ManyToManyField(blank=True, null=True, through='active.ActiveCoursePeriod', to='timetable.periods'),
        ),
        migrations.AddField(
            model_name='activecourse',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='active.instructor'),
        ),
    ]
