# Generated by Django 3.2.18 on 2023-07-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TakenCourse',
        ),
    ]
