# Generated by Django 3.2.18 on 2024-01-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0002_instructor_shiftchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecourse',
            name='ShiftChoices',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Nght'), ('Any', 'Any')], default='Any', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pupl',
            name='ShiftChoices',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Nght'), ('Any', 'Any')], default='Any', max_length=100, null=True),
        ),
    ]
