# Generated by Django 3.2.18 on 2024-01-15 02:27

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0003_auto_20240114_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourseperiod',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
