# Generated by Django 3.2.18 on 2024-01-15 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0004_alter_activecourseperiod_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecourseperiod',
            name='additional_field',
        ),
    ]
