# Generated by Django 3.2.18 on 2024-01-15 02:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0005_remove_activecourseperiod_additional_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourseperiod',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
