# Generated by Django 3.2.18 on 2023-09-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0005_activecourse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecourse',
            name='payment',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
    ]
