# Generated by Django 3.2.18 on 2024-01-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_periods_shiftchoices'),
        ('active', '0006_alter_activecourseperiod_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activecourseperiod',
            unique_together={('teacher', 'period')},
        ),
    ]
