# Generated by Django 3.2.18 on 2023-09-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0045_auto_20230913_0511'),
        ('active', '0006_activecourse_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourse',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.staff'),
        ),
    ]
