# Generated by Django 3.2.18 on 2024-02-28 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0007_alter_activecourseperiod_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField(default=False)),
                ('active_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active.activecourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active.pupl')),
            ],
        ),
    ]
