# Generated by Django 3.2.18 on 2023-09-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_img'),
        ('active', '0007_alter_activecourse_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
