# Generated by Django 3.2.18 on 2023-10-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0009_activecourse_capicty'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecourse',
            name='enrolled',
            field=models.IntegerField(null=True),
        ),
    ]
