# Generated by Django 3.2.18 on 2024-02-29 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0010_auto_20240228_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_created',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.CharField(choices=[('attended', 'Attended'), ('cancelled_teacher', 'Cancelled by Teacher'), ('cancelled_student', 'Cancelled by Student')], default='attended', max_length=20, null=True)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active.attendance')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active.pupl')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ManyToManyField(through='active.AttendanceRecord', to='active.pupl'),
        ),
    ]
