# Generated by Django 3.2.18 on 2024-03-07 05:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0011_auto_20240229_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attended',
            field=models.CharField(choices=[('not chosen', 'Not chosen'), ('attended', 'Attended'), ('cancelled_teacher', 'Cancelled by Teacher'), ('cancelled_student', 'Cancelled by Student')], default='not chosen', max_length=20, null=True),
        ),
    ]
