# Generated by Django 3.2.18 on 2023-10-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0046_auto_20230925_0429'),
        ('active', '0011_auto_20231022_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupl',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pupl',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pupl',
            name='periods',
        ),
        migrations.RemoveField(
            model_name='pupl',
            name='phone',
        ),
        migrations.AddField(
            model_name='pupl',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.student'),
        ),
    ]
