# Generated by Django 3.2.18 on 2023-10-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0012_auto_20231022_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecourse',
            name='student',
        ),
    ]
