# Generated by Django 3.2.18 on 2023-10-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0013_remove_activecourse_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupl',
            name='payment',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
    ]
