# Generated by Django 3.2.18 on 2023-12-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0019_auto_20231206_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecourse',
            name='course_class_id',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
