# Generated by Django 3.2.18 on 2023-12-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0020_activecourse_course_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecourse',
            name='course_class_id',
        ),
    ]
