# Generated by Django 3.2.18 on 2023-12-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0022_activecourse_course_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourse',
            name='course_class_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
