# Generated by Django 3.2.18 on 2023-12-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0027_auto_20231216_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='title',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='twitter',
        ),
    ]
