# Generated by Django 3.2.18 on 2023-12-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0030_instructor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourse',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='active.instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
