# Generated by Django 3.2.18 on 2023-12-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0034_alter_activecourse_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourse',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
