# Generated by Django 3.2.18 on 2023-12-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0035_alter_activecourse_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourse',
            name='full',
            field=models.BooleanField(null=True),
        ),
    ]
