# Generated by Django 3.2.18 on 2023-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_auto_20230625_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='capcity',
            field=models.PositiveIntegerField(default=0, null=0),
        ),
    ]
