# Generated by Django 3.2.18 on 2023-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0021_takencourse_capcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takencourse',
            name='capcity',
            field=models.PositiveIntegerField(default=1, null=0),
        ),
    ]
