# Generated by Django 3.2.18 on 2023-07-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0029_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
    ]
