# Generated by Django 3.2.18 on 2023-07-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0034_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='period2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='period3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='period4',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
