# Generated by Django 3.2.18 on 2023-07-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_img'),
        ('team', '0042_alter_student_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
