# Generated by Django 3.2.18 on 2023-07-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0043_student_courses'),
        ('courses', '0005_alter_course_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('Course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ManyToManyField(to='team.Student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.staff')),
            ],
        ),
    ]
