# Generated by Django 3.2.18 on 2023-07-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0043_student_courses'),
        ('courses', '0005_alter_course_img'),
        ('timetable', '0019_delete_takencourse'),
        ('active', '0002_delete_takencourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('Course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('periods', models.ManyToManyField(blank=True, null=True, to='timetable.periods')),
                ('student', models.ManyToManyField(to='team.Student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.staff')),
            ],
        ),
    ]
