# Generated by Django 3.2.18 on 2023-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_img'),
        ('team', '0003_staff_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
