# Generated by Django 3.2.18 on 2023-07-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0003_activecourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activecourse',
            old_name='Course',
            new_name='course',
        ),
    ]
