# Generated by Django 3.2.18 on 2023-06-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_staff_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='team.staff')),
            ],
        ),
    ]
