# Generated by Django 3.2.18 on 2023-06-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20230625_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AlterField(
            model_name='takencourse',
            name='students',
            field=models.ManyToManyField(to='team.Student'),
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
