# Generated by Django 3.2.18 on 2023-06-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20230625_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takencourse',
            name='students',
        ),
    ]
