# Generated by Django 3.2.18 on 2023-10-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0014_pupl_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupl',
            name='student',
        ),
        migrations.AddField(
            model_name='pupl',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pupl',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pupl',
            name='phone',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
