# Generated by Django 3.2.18 on 2023-12-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_auto_20230917_0528'),
        ('active', '0016_alter_pupl_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupl',
            name='periods',
            field=models.ManyToManyField(blank=True, null=True, to='timetable.periods'),
        ),
    ]
