# Generated by Django 3.2.18 on 2023-06-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_auto_20230625_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takencourse',
            options={'verbose_name_plural': 'Taken Courses'},
        ),
    ]
