# Generated by Django 3.2.18 on 2023-12-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0017_pupl_periods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupl',
            name='periods',
        ),
    ]
