# Generated by Django 3.2.18 on 2023-06-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_auto_20230625_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takencourse',
            name='capacity',
        ),
    ]
