# Generated by Django 3.2.18 on 2023-12-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0021_remove_activecourse_course_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecourse',
            name='course_class_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
