# Generated by Django 3.2.18 on 2023-06-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0023_rename_capcity_takencourse_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='period',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='takencourse',
            name='capacity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
