# Generated by Django 3.2.18 on 2023-12-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0023_alter_activecourse_course_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecourse',
            name='end_date',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='activecourse',
            name='start_date',
            field=models.TimeField(null=True),
        ),
    ]
