# Generated by Django 3.2.18 on 2023-12-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0024_auto_20231215_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourse',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activecourse',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
