# Generated by Django 3.2.18 on 2023-12-15 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0025_auto_20231215_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourse',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activecourse',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activecourse',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('On site', 'On site'), ('On site', 'On site')], default='online', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pupl',
            name='active',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='active.activecourse'),
        ),
    ]
