# Generated by Django 3.2.18 on 2023-07-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0026_takencourse_end_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TakenCourse',
        ),
    ]
