# Generated by Django 3.2.18 on 2023-12-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0028_auto_20231216_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='password',
        ),
    ]
