# Generated by Django 3.2.18 on 2023-12-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0029_auto_20231217_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
