# Generated by Django 3.2.18 on 2023-12-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0031_auto_20231217_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
