# Generated by Django 3.2.18 on 2023-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0031_auto_20230703_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='period',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
