# Generated by Django 3.2.18 on 2023-07-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0033_takencourse_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period1', models.DateTimeField(null=True)),
                ('period2', models.DateTimeField(null=True)),
                ('period3', models.DateTimeField(null=True)),
                ('period4', models.DateTimeField(null=True)),
            ],
        ),
    ]
