# Generated by Django 3.2.18 on 2023-07-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0035_auto_20230703_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
    ]
