# Generated by Django 3.2.18 on 2023-12-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0036_alter_activecourse_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecourse',
            name='full',
        ),
    ]
