# Generated by Django 3.2.18 on 2023-07-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0036_delete_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TakenCourse',
        ),
    ]
