# Generated by Django 3.2.18 on 2024-01-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0037_remove_activecourse_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecourse',
            name='capacity',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='activecourse',
            name='type',
            field=models.CharField(choices=[('online', 'online'), ('On site', 'On site')], default='online', max_length=100, null=True),
        ),
    ]
