# Generated by Django 3.2.18 on 2023-07-07 09:58

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_delete_takencourse'),
        ('team', '0038_staff_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='periods',
            field=models.ManyToManyField(to='timetable.periods'),
        ),
    ]
