# Generated by Django 3.2.18 on 2023-07-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_delete_takencourse'),
        ('team', '0043_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='periods',
            field=models.ManyToManyField(null=True, to='timetable.periods'),
        ),
    ]
