# Generated by Django 3.2.18 on 2023-12-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0046_auto_20230925_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('instructor', 'instructor'), ('Not intstuctor', 'Not intstuctor')], max_length=100, null=True),
        ),
    ]
