# Generated by Django 3.2.18 on 2024-01-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseDetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to='images')),
                ('coursedetails', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseDetail.coursedetails')),
            ],
        ),
    ]
