# Generated by Django 3.2.18 on 2023-06-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0021_coursedetails_price'),
        ('courses', '0002_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursedetails',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseDetail.coursedetails'),
        ),
    ]
