# Generated by Django 3.2.18 on 2023-06-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_coursedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
