# Generated by Django 3.2.18 on 2024-01-11 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numberOfPeriods', models.PositiveIntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(16)])),
                ('numOfweek', models.PositiveIntegerField(default=7, null=True, validators=[django.core.validators.MaxValueValidator(52)])),
            ],
        ),
        migrations.CreateModel(
            name='periods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('start_at', models.TimeField(null=True)),
                ('end_at', models.TimeField(blank=True, null=True)),
                ('Classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Classes', to='timetable.classes')),
            ],
        ),
    ]
