# Generated by Django 3.2.18 on 2024-01-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periods',
            name='ShiftChoices',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Nght'), ('Any', 'Any')], default='Any', max_length=100, null=True),
        ),
    ]
