# Generated by Django 3.2.18 on 2023-07-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TakenCourse',
        ),
    ]
