# Generated by Django 3.2.18 on 2023-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0002_delete_takencourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period1', models.DateTimeField(blank=True, null=True)),
                ('period2', models.DateTimeField(blank=True, null=True)),
                ('period3', models.DateTimeField(blank=True, null=True)),
                ('period4', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
