# Generated by Django 3.2.18 on 2023-07-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0037_delete_takencourse'),
        ('courses', '0005_alter_course_img'),
        ('timetable', '0003_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=5, null=True)),
                ('period', models.PositiveIntegerField(default=1, null=True)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('Student', models.ManyToManyField(null=True, to='team.Student')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.staff')),
            ],
        ),
    ]
