# Generated by Django 3.2.18 on 2023-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_takencourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_start', models.DateTimeField(blank=True, null=True)),
                ('classes_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
