# Generated by Django 3.2.18 on 2023-07-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='period1',
        ),
        migrations.RemoveField(
            model_name='period',
            name='period2',
        ),
        migrations.RemoveField(
            model_name='period',
            name='period3',
        ),
        migrations.RemoveField(
            model_name='period',
            name='period4',
        ),
        migrations.AddField(
            model_name='period',
            name='classes',
            field=models.ManyToManyField(to='timetable.classes'),
        ),
    ]
