# Generated by Django 3.2.18 on 2023-07-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20230704_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='classes',
        ),
        migrations.DeleteModel(
            name='classes',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
