# Generated by Django 3.2.18 on 2023-07-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20230704_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='periods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('Classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classes', to='timetable.classes')),
            ],
        ),
    ]
