# Generated by Django 3.2.18 on 2023-07-04 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20230704_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='days',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='classes',
            name='numberOfPeriods',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(16)]),
        ),
    ]
