# Generated by Django 3.2.18 on 2023-07-04 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_auto_20230704_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='days',
            field=models.PositiveIntegerField(default=7, null=True, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='classes',
            name='numberOfPeriods',
            field=models.PositiveIntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(16)]),
        ),
    ]
