# Generated by Django 3.2.18 on 2023-07-05 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_periods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='numOfweek',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(52)]),
        ),
    ]
