# Generated by Django 3.2.18 on 2023-07-05 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_classes_numofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='numOfweek',
            field=models.PositiveIntegerField(default=7, null=True, validators=[django.core.validators.MaxValueValidator(52)]),
        ),
    ]
