# Generated by Django 3.2.18 on 2023-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_periods_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periods',
            name='end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periods',
            name='start_at',
            field=models.TimeField(null=True),
        ),
    ]
