# Generated by Django 3.2.18 on 2023-07-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_auto_20230705_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TakenCourse',
        ),
    ]
