# Generated by Django 3.2.18 on 2023-09-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_delete_takencourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100, null=True)),
            ],
        ),
    ]
