# Generated by Django 3.2.18 on 2023-09-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0020_courseperiods'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMPeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField(null=True)),
                ('end_at', models.TimeField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CoursePeriods',
            new_name='CourseMonths',
        ),
    ]
