# Generated by Django 3.2.18 on 2023-09-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_auto_20230917_0521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMonths',
        ),
        migrations.DeleteModel(
            name='CourseMPeriods',
        ),
    ]
