# Generated by Django 3.2.18 on 2023-06-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overView', models.TextField(null=True)),
                ('Course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('audience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseDetail.audience')),
            ],
        ),
    ]
