# Generated by Django 3.2.18 on 2023-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='audience',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='audience',
            field=models.ManyToManyField(null=True, to='courseDetail.Audience'),
        ),
    ]
