# Generated by Django 3.2.18 on 2023-06-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0003_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='requirement',
            field=models.ManyToManyField(null=True, to='courseDetail.Requirement'),
        ),
    ]
