# Generated by Django 3.2.18 on 2023-06-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0004_coursedetails_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='audience',
            field=models.ManyToManyField(to='courseDetail.Audience'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='requirement',
            field=models.ManyToManyField(to='courseDetail.Requirement'),
        ),
    ]
