# Generated by Django 3.2.18 on 2023-06-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0008_auto_20230621_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='module',
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courseDetail.module'),
        ),
        migrations.RemoveField(
            model_name='module',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='module',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courseDetail.curriculum'),
        ),
    ]
