# Generated by Django 3.2.18 on 2023-06-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0009_auto_20230621_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='module',
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='module',
            name='curriculum',
        ),
        migrations.DeleteModel(
            name='Audience',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='CourseDetails',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
