# Generated by Django 3.2.18 on 2023-06-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0011_chapter_curriculum_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='Module',
        ),
        migrations.AddField(
            model_name='module',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseDetail.curriculum'),
        ),
    ]
