# Generated by Django 3.2.18 on 2023-06-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0013_auto_20230622_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseDetail.curriculum'),
        ),
    ]
