# Generated by Django 3.2.18 on 2023-06-22 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0014_chapter_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='module',
        ),
        migrations.AddField(
            model_name='module',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseDetail.chapter'),
        ),
    ]
