# Generated by Django 3.2.18 on 2023-06-22 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0016_auto_20230622_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='curriculum',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
