# Generated by Django 3.2.18 on 2023-06-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0018_curriculum_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='Chapter',
            field=models.ManyToManyField(related_name='chapter', to='courseDetail.Chapter'),
        ),
    ]
