# Generated by Django 3.2.18 on 2023-06-22 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0019_auto_20230622_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('overview', models.TextField(null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('audience', models.ManyToManyField(to='courseDetail.Audience')),
                ('curriculum', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseDetail.curriculum')),
                ('requirements', models.ManyToManyField(to='courseDetail.Requirement')),
            ],
        ),
    ]
