# Generated by Django 3.2.18 on 2023-06-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0020_audience_coursedetails_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
