# Generated by Django 3.2.18 on 2023-06-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseDetail', '0021_coursedetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='name',
        ),
    ]
