# Generated by Django 3.2.18 on 2023-06-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20230624_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
