# Generated by Django 3.2.18 on 2023-06-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_certifcation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='certifcation',
        ),
    ]
