# Generated by Django 3.2.18 on 2023-06-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20230625_0305'),
    ]

    operations = [
    ]
