# Generated by Django 3.2.18 on 2023-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_remove_takencourse_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='student',
            field=models.ManyToManyField(to='team.Student'),
        ),
        migrations.AlterField(
            model_name='takencourse',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
