# Generated by Django 3.2.18 on 2023-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_alter_takencourse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takencourse',
            options={},
        ),
        migrations.AlterField(
            model_name='takencourse',
            name='capacity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
