# Generated by Django 3.2.18 on 2023-06-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0022_alter_takencourse_capcity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takencourse',
            old_name='capcity',
            new_name='capacity',
        ),
    ]
