# Generated by Django 3.2.18 on 2023-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0024_auto_20230625_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
