# Generated by Django 3.2.18 on 2023-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0030_delete_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takencourse',
            name='period',
        ),
        migrations.AlterField(
            model_name='takencourse',
            name='capacity',
            field=models.PositiveIntegerField(default=5, null=True),
        ),
    ]
