# Generated by Django 3.2.18 on 2023-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_delete_takencourse'),
        ('team', '0037_delete_takencourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='periods',
            field=models.ManyToManyField(to='timetable.periods'),
        ),
    ]
